package by.maksim.curse_work.util;

public class Constants {
    public static final String CREATE_TABLE_DEVICES =
            """
                CREATE TABLE IF NOT EXISTS devices (
                        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        designation VARCHAR(64) NOT BULL,
                        number INT NOT NULL,
                        condition VARCHAR(64) NOT NULL
                    );
                """;

    public static final String CREATE_TABLE_EMPLOYEES =
            """
                CREATE TABLE IF NOT EXISTS employees (
                        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        surname VARCHAR(64) NOT NULL,
                        name VARCHAR(64) NOT NULL,
                        patronymic VARCHAR(64) NOT NULL,
                        job_title VARCHAR(64) NOT NULL,
                        access_level INT NOT NULL,
                        card_condition VARCHAR(64) NOT NULL
                    );
                """;
}
